run flask server and I'm insun's update
doorooful/CapstoneProject pull request #110
Opened 2023-09-16 00:01 UTC by leeinsunny

I add " pip install requests " to README.ME

2023-09-16 00:14 UTC, doorooful commented on dt-demo-be/README.md
>  (.venv) CapstoneProject % pip install flask-cors
Can you add pip install pandas as you told so?

2023-09-16 00:15 UTC, doorooful requested changes
It'd be better to capture screen shot and share on comments!

2023-09-18 06:35 UTC, leeinsunny commented on dt-demo-be/README.md
>  (.venv) CapstoneProject % pip install flask-cors
okay~!!

2023-09-18 06:36 UTC, leeinsunny commented
Alright~!

2023-09-18 06:38 UTC, leeinsunny reviewed
okay!

2023-09-23 12:47 UTC, closed without merging