upload input files' info
doorooful/CapstoneProject pull request #125
Opened 2023-09-20 16:13 UTC by yoouung

- enhancement needed to transmit file object to server

2023-09-20 16:19 UTC, yoouung commented
1. file upload
<img width="1330" alt="image" src="https://github.com/doorooful/CapstoneProject/assets/78146904/77067f22-0b5b-4188-b21a-89ef1bddadb3">

2. server response
<img width="1330" alt="image" src="https://github.com/doorooful/CapstoneProject/assets/78146904/e6f63f48-37c0-40d0-acad-e114d6dafb3f">

2023-09-20 16:22 UTC, yoouung commented
postman status
<img width="844" alt="image" src="https://github.com/doorooful/CapstoneProject/assets/78146904/00fe35fb-6162-46ad-aa1c-051289e71d72">

2023-09-20 16:32 UTC, doorooful requested changes
I'd like to discuss about 2  things regarding comments!
1 - Separating this PR into 2 PRs
2 - Users' scenario and logging level
We may discuss tomorrow or further 🥹

2023-09-20 16:32 UTC, doorooful commented on dt-demo-be/app.py
> +@app.route("/api/filter/filelist", methods=["GET"])
Is this line for file uploading?
I think It'd better to separate these changes to visualize file list

2023-09-20 16:32 UTC, doorooful commented on dt-demo-fe/src/components/file/uploadBtn.js
> +            console.log("No file selected");
Could you use 'console.warn()' function in terms of handling unexpected behavior?
Or we may discuss further about the requirements!

2023-09-21 05:18 UTC, yoouung commented on dt-demo-be/app.py
> +@app.route("/api/filter/filelist", methods=["GET"])
uploaded separate PR for this issue

2023-09-21 05:18 UTC, yoouung commented on dt-demo-fe/src/components/file/uploadBtn.js
> +            console.log("No file selected");
it is for when user clicked `cancel` button, so I just modified the log message.

2023-09-21 06:21 UTC, doorooful approved these changes
🥰

2023-09-21 06:36 UTC, merged