create new folder(spc) and run.py under the spc
doorooful/CapstoneProject pull request #134
Opened 2023-09-22 14:51 UTC by OSsunNO

A.C:

- create a new folder for special character module under the /modules

- create a run.py referring the structure of dup/run.py under the folder for special character

2023-09-22 14:56 UTC, doorooful reviewed
Can you copy and paste the result screenshot on comment?

2023-09-22 15:35 UTC, OSsunNO commented
spc API server test is successfully completed.
![image](https://github.com/doorooful/CapstoneProject/assets/87080270/64c89bd5-7c55-4b22-a826-3b451c028075)

2023-09-22 15:47 UTC, doorooful requested changes
Please refer to the comment 😀

2023-09-22 15:47 UTC, doorooful commented on dt-demo-be/modules/spc/run.py
> +    # TODO: Implement spc substitution logic
I think it'd be better to implement the code of creating new {inputFile}_filtered.txt with no changes(just copy the contents of given input data),
and add Todo statement on the line where it would affect changes on editing contents.

2023-09-22 16:21 UTC, OSsunNO commented on dt-demo-be/modules/spc/run.py
> +    # TODO: Implement spc substitution logic
- Result for the code of creating new {inputFile}_filtered.txt with no changes
![image](https://github.com/doorooful/CapstoneProject/assets/87080270/5483ffe8-51f3-400c-a56f-cf585444f28a)
- Result for server request
![image](https://github.com/doorooful/CapstoneProject/assets/87080270/c1ea65c8-bdde-4e58-b82c-24e6251d156e)
- Result of server running
![image](https://github.com/doorooful/CapstoneProject/assets/87080270/a35ffad5-e071-4259-bfe7-175e189d97ef)

2023-09-22 16:24 UTC, doorooful approved these changes
Thanks for your effort 🥹

2023-09-22 16:26 UTC, merged

2023-09-23 11:22 UTC, leeinsunny commented
gooood~!