Implement spc(special character replacing) module
doorooful/CapstoneProject pull request #151
Opened 2023-09-24 19:17 UTC by OSsunNO

Partially completed tasks:

1. define 'spc_dict' - initial version

2. Implement the logic to replace special character

TODO: Check the running time of spc module using test data ('seoul_freeboard.csv')

2023-09-24 19:53 UTC, OSsunNO commented
- spc_dict file is not uploaded, so I uploaded it to our google drive (2023 Capstone)

- testing 1
   1) original data
![image](https://github.com/doorooful/CapstoneProject/assets/87080270/34ee949d-7a53-4ba1-b7be-d7c42c411147)
   2) converted data
![image](https://github.com/doorooful/CapstoneProject/assets/87080270/4b5a0d5b-883b-4fda-923f-505f8339f8d0)
   3) module running time
![image](https://github.com/doorooful/CapstoneProject/assets/87080270/8e63f7e6-f55d-47be-90ab-f319f8c7e285)

- testing 2
   1) original data
![image](https://github.com/doorooful/CapstoneProject/assets/87080270/e4d99c14-8480-4a07-89aa-0161dce77c28)
   2) converted data
![image](https://github.com/doorooful/CapstoneProject/assets/87080270/75bb64a1-1313-41d3-a5a6-b6987ccb5788)
   3) module running time
![image](https://github.com/doorooful/CapstoneProject/assets/87080270/3c530e82-2598-49d0-b8b2-96c458c53262)

2023-09-25 00:08 UTC, doorooful requested changes
I request little change on displaying time spent of the module! Also, can you upload dictionary xlsx file on PR comment?
Thanks for your work!!!

2023-09-25 00:08 UTC, doorooful commented on dt-demo-be/modules/spc/run.py
> +    print(f"{end-start:.5f} sec")
Can you put description here?
i.e) f'Total running time of spc module: {end-start} sec'

2023-09-25 00:55 UTC, yoouung commented on dt-demo-be/modules/spc/run.py
> +    test_dict = pd.read_csv("/mnt/c/Users/user/VSProjects/CapstoneProject/database/seoul_freeboard.csv")
Can you change the file path from absolute to relative?

2023-09-25 07:50 UTC, OSsunNO commented on dt-demo-be/modules/spc/run.py
> +    print(f"{end-start:.5f} sec")
output:
![image](https://github.com/doorooful/CapstoneProject/assets/87080270/5c5b0302-ec25-4e4c-9c5c-a9a56cf0282b)

2023-09-25 07:51 UTC, OSsunNO commented on dt-demo-be/modules/spc/run.py
> +    test_dict = pd.read_csv("/mnt/c/Users/user/VSProjects/CapstoneProject/database/seoul_freeboard.csv")
Modified code:
![image](https://github.com/doorooful/CapstoneProject/assets/87080270/8db93dfe-0dc4-4409-bf07-321edbf4f86c)

2023-09-25 07:57 UTC, doorooful commented
[spc_dict_v1.xlsx](https://github.com/doorooful/CapstoneProject/files/12712577/spc_dict_v1.xlsx)

2023-09-25 08:02 UTC, merged

2023-09-25 08:02 UTC, yoouung commented
LGTM!