detection report viewer
doorooful/CapstoneProject pull request #155
Opened 2023-09-26 08:33 UTC by yoouung

- frontend
  - modify stylesheet `href` from _local path_ to _bootstrap link_ in html template
  - add pdf frame in detection report page
  - (auto formatting for HTML with `prettier` extension)
- docs
  - update README.md for additional library install

2023-09-26 08:37 UTC, yoouung commented
![image](https://github.com/doorooful/CapstoneProject/assets/78146904/c30e3ef0-acc4-4b6c-9253-e080eb156d5d)

2023-09-26 15:21 UTC, doorooful requested changes
Can you confirm the alert message?

2023-09-26 15:21 UTC, doorooful commented on dt-demo-fe/src/pages/filtering/detectionReport.js
> +            alert("필터링이 완료되었습니다.");
Can you confirm the message?

2023-09-27 02:41 UTC, yoouung commented on dt-demo-fe/src/pages/filtering/detectionReport.js
> +            alert("필터링이 완료되었습니다.");
I changed the message!
please check the updated code.
thanks for your check :)

2023-09-27 02:50 UTC, doorooful approved these changes
LGTM!👍

2023-09-27 02:57 UTC, merged