upload file from frontend to backend
doorooful/CapstoneProject pull request #167
Opened 2023-09-30 17:05 UTC by yoouung

- frontend
  - update file transfer method
  - add axios interceptor for file transfer
  - remove unnecessary code lines in `filelist.js`
- backend
  - update `file_upload()`

2023-09-30 17:08 UTC, yoouung commented
If you refer to the server code line, you can get the following result:
<img width="425" alt="image" src="https://github.com/doorooful/CapstoneProject/assets/78146904/3455cc0a-9f4e-44cf-943f-7c32e86c3b72">

2023-09-30 17:36 UTC, OSsunNO approved these changes
You are such a great person! Good job😃

2023-10-01 03:19 UTC, doorooful requested changes
I think to log file name information would be better on api request. Please refer to the comments.

2023-10-01 03:19 UTC, doorooful commented on dt-demo-be/app.py
> +            "file": {
Do you have any plans of if user has sent multiple numbers of files?

2023-10-01 03:19 UTC, doorooful commented on dt-demo-be/app.py
> +            app.logger.info(f"first 20 characters: %s", first_20_characters)
I think it'd be better to log server status with file name rather than contents.
Though thanks for ensuring data quality here.

2023-10-01 03:19 UTC, doorooful commented on dt-demo-be/app.py
> +        if uploaded_file.filename != '':
I'd recommend to use 'isFileExists' or similar variable  name for this statement

''' example
isFileExists = uploaded_file.filename != ""

if isFileExists:
    # statement body
'''

2023-10-01 11:23 UTC, yoouung commented
@doorooful thanks for your comments!

here is the result of updated version server
<img width="512" alt="image" src="https://github.com/doorooful/CapstoneProject/assets/78146904/e8baacd3-f439-4145-8629-404c602fbc73">

2023-10-01 15:43 UTC, doorooful approved these changes
LGTM

2023-10-02 00:48 UTC, merged