converter page layout develop
doorooful/CapstoneProject pull request #204
Opened 2023-10-10 07:30 UTC by yoouung

- updated converter page design and layout
- fix bugs related to filtering pages

2023-10-10 07:30 UTC, yoouung commented
converter page :
<img width="1582" alt="image" src="https://github.com/doorooful/CapstoneProject/assets/78146904/c18cc219-0189-4d67-9cd2-ece7e79b7751">

2023-10-10 07:39 UTC, doorooful reviewed
Can you keep consistency of filetree naming?
i.e)
```
src/
    pages/
        converter/
            index.js
            conversionReport.js
            realtime.js
        filter/
            index.js
```

2023-10-12 01:44 UTC, yoouung commented
1. upload
<img width="1562" alt="image" src="https://github.com/doorooful/CapstoneProject/assets/78146904/e367eca8-5cae-4207-b08a-1ea3bacb7417">

2. alert
<img width="1562" alt="image" src="https://github.com/doorooful/CapstoneProject/assets/78146904/af986c4f-cbc2-4d72-83ce-cbe8843c26cb">

3. window reload -> file list update
<img width="1562" alt="image" src="https://github.com/doorooful/CapstoneProject/assets/78146904/5f48e6ed-bb2a-4cd7-94e3-5162212d280a">

2023-10-12 05:45 UTC, doorooful requested changes
Please review my comments. Thank you!!

2023-10-12 05:45 UTC, doorooful commented on dt-demo-fe/src/Router.js
> +                    <Route path="conversion" element={<ConversionContainer />} />
Is this line changed?

2023-10-12 05:45 UTC, doorooful commented on dt-demo-be/app_lab.py
> +from flask import Flask, jsonify, request
Thanks 😁

2023-10-12 05:45 UTC, doorooful commented on dt-demo-be/app_lab.py
> +    created_doc.fetchConvReportInfo(db_conn, data['option'])
I don't think this would work well.
fetching conv report info requires to fetch det report info.
Can you confirm?

2023-10-12 05:45 UTC, doorooful commented on dt-demo-fe/src/pages/converter/realtime.js
> +            <TextArea className="textarea" value={output} disabled />
Can you set default output as user input?

2023-10-12 06:32 UTC, yoouung commented on dt-demo-fe/src/Router.js
> +                    <Route path="conversion" element={<ConversionContainer />} />
yes, but I removed the line breaks and made it into one line

2023-10-12 06:38 UTC, yoouung commented on dt-demo-be/app_lab.py
> +    created_doc.fetchConvReportInfo(db_conn, data['option'])
I didn't implement report generating function, so this api is not working right now
therefore actually I don't know if this api is working well. so I just removed it 
please check!

2023-10-12 06:48 UTC, yoouung commented on dt-demo-fe/src/pages/converter/realtime.js
> +            <TextArea className="textarea" value={output} disabled />
I added the placeholder in this tag
<img width="426" alt="image" src="https://github.com/doorooful/CapstoneProject/assets/78146904/6e459bb1-8715-4d35-9daa-fbf48cf86053">

2023-10-12 07:06 UTC, doorooful approved these changes
Looks good to me!

2023-10-12 07:10 UTC, merged