Issue28/api key management
doorooful/CapstoneProject pull request #30
Opened 2023-03-30 06:47 UTC by doorooful

For the implementation convenience, I've added api key management concept on the project ◡̈

2023-03-30 07:33 UTC, yoouung requested changes

2023-03-30 07:33 UTC, yoouung commented on README.md
> +`% export {APINAME}_API_KEY='{API KEY VALUE}`
needed to be permanent variable.

2023-04-16 05:33 UTC, doorooful commented on README.md
> +`% export {APINAME}_API_KEY='{API KEY VALUE}`
Applied◡̈

2023-04-16 05:37 UTC, yoouung approved these changes
:)

2023-04-16 05:38 UTC, merged