Issue91 button implementation
doorooful/CapstoneProject pull request #94
Opened 2023-09-10 15:00 UTC by yoouung

2023-09-10 15:29 UTC, doorooful requested changes
Could you modify commit message?

2023-09-10 15:32 UTC, doorooful commented on dt-demo-fe/src/pages/demo/upload.js
> +// import UploadBtn from "../../components/File/uploadBtn";
Can you remove unnecessary line?

2023-09-10 15:34 UTC, doorooful commented on dt-demo-fe/src/Router.js
> +                <Route path="/" element={<Navigate replace to="/upload" />} />
Can you move these routes under `/filter`?
i.e. `/filter/upload`, `/filter/filelist`

2023-09-11 03:01 UTC, yoouung commented on dt-demo-fe/src/pages/demo/upload.js
> +// import UploadBtn from "../../components/File/uploadBtn";
checked!

2023-09-11 03:01 UTC, yoouung commented on dt-demo-fe/src/Router.js
> +                <Route path="/" element={<Navigate replace to="/upload" />} />
checked!
I added __Outlet__ component in `02_filter.js`

2023-09-11 03:07 UTC, yoouung commented
# /filter
<img width="996" alt="image" src="https://github.com/doorooful/CapstoneProject/assets/78146904/9e042c52-7789-4391-994f-2a48b6fdfdc6">

# /filter/filelist
<img width="997" alt="image" src="https://github.com/doorooful/CapstoneProject/assets/78146904/84c4e582-496b-42e6-aadf-bf9836223ceb">

# /filter/rules
<img width="989" alt="image" src="https://github.com/doorooful/CapstoneProject/assets/78146904/533335ec-dcae-48ab-8629-af3ed1d0ae6a">

# /filter/report
<img width="1008" alt="image" src="https://github.com/doorooful/CapstoneProject/assets/78146904/22c52d91-4d64-4644-a3a4-faef5583bcf6">

2023-09-11 03:15 UTC, doorooful commented
Thanks for your effort☺️

2023-09-11 03:16 UTC, doorooful approved these changes

2023-09-11 03:21 UTC, merged