Filtering Rules Implementation
doorooful/CapstoneProject pull request #99
Opened 2023-09-13 15:34 UTC by yoouung

- Implementation on frontend details and server

2023-09-15 13:30 UTC, yoouung commented
### 1. Selecting option
<img width="822" alt="image" src="https://github.com/doorooful/CapstoneProject/assets/78146904/3081fa41-6fcc-496f-9bd4-8ce5d4e4920b">

### 2. Alert for success
<img width="463" alt="image" src="https://github.com/doorooful/CapstoneProject/assets/78146904/85879673-e112-43fc-977d-0efca2d178b3">

### 3. Result
`original data`
<img width="309" alt="image" src="https://github.com/doorooful/CapstoneProject/assets/78146904/fe689eea-3e5f-4926-ab75-d1490e50a109">
`filtered data`
<img width="303" alt="image" src="https://github.com/doorooful/CapstoneProject/assets/78146904/442d3c8e-8f2b-4697-8998-781858987848">

2023-09-15 14:04 UTC, doorooful requested changes
I request changes according to the comments ◡̈

2023-09-15 14:04 UTC, doorooful commented on dt-demo-be/app.py
> +        # args = sampleArgs1
Please remove unnecessary lines and replace them into comments!

2023-09-15 14:04 UTC, doorooful commented on dt-demo-be/app.py
> +        return "Filtering done"
I think `"filtering requested"` would be better

2023-09-15 14:04 UTC, doorooful commented on dt-demo-fe/package.json
> +    "proxy": "http://localhost:5001",
Could you test this line?

2023-09-15 14:04 UTC, doorooful commented on dt-demo-fe/src/components/Rules/ruleOptions.js
> +    // {
Please remove not used lines!

2023-09-15 14:15 UTC, doorooful commented on dt-demo-fe/package.json
> +        "fs": "^0.0.1-security",
Can you check if npm installing command is needed?

2023-09-15 14:16 UTC, doorooful requested changes
Please find the comment!!

2023-09-15 14:18 UTC, doorooful approved these changes
LGTM!!

2023-09-15 14:18 UTC, merged

2023-09-18 05:55 UTC, doorooful commented
Please use following sample data as follows
```JSON
{
    "form": {
        "all": false,
        "modules": "typo,pdd",
        "input": "demo.txt"
    }
}
```

![image](https://github.com/doorooful/CapstoneProject/assets/110809138/9d961b4a-a676-4178-9dcd-081e92bdc3a5)